source 'https://rubygems.org'

gem 'rails'
gem 'bootstrap-sass', '2.3.2.0'
gem 'sprockets'
gem 'bcrypt-ruby', '3.1.2'

group :development, :test do
  gem 'sqlite3'
  gem 'rspec-rails'
end

# Gems used only for assets and not required
# in production environments by default.
group :assets do
  gem 'sass-rails'  
  gem 'coffee-rails'
  gem 'uglifier'
  gem 'turbolinks'
  gem 'jbuilder'
  gem 'jquery-rails'
end

#gem 'jquery-rails'

group :test do
  gem 'capybara'
  gem 'launchy'
  gem 'factory_girl_rails', '4.2.0' 
end

group :development do
  gem 'annotate'
end
group :production do
  gem 'pg'
end
