source 'https://rubygems.org'

gem 'rails'
gem 'bootstrap-sass'
gem 'sprockets'

group :development, :test do
  gem 'sqlite3'
  gem 'rspec-rails'
end

# Gems used only for assets and not required
# in production environments by default.
group :assets do
  gem 'sass-rails'  
  gem 'coffee-rails'
  gem 'uglifier'
  gem 'turbolinks'
  gem 'jbuilder'
  gem 'jquery-rails'
end

gem 'jquery-rails'

group :test do
  gem 'capybara'
  gem 'launchy' 
end

group :production do
  gem 'pg'
end
