# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c37eb21d7bf614aeffd24edd72efa86ab1043fdfea8f40efcdd8136bbbed4418808ec17dd76fb0cd53dd2e32d9dac20606364baf49e33c9f779f432efaf4c5c9

test:
  secret_key_base: 002d60c8df2a083455eab45228b82bdcc98bf6dfd1847631629437b7e51e86f3fc020713e61e8c067c6e2863e0a7d357fc78cab631fb9e98b863101f5a0121b9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
